/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade1;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 277029
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nome1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        cidade = new javax.swing.JLabel();
        opt_masc = new javax.swing.JRadioButton();
        opt_fem = new javax.swing.JRadioButton();
        turma = new javax.swing.JLabel();
        cbo_turma = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        obs = new javax.swing.JTextArea();
        chk_atv_des = new javax.swing.JCheckBox();
        btn_cadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cadastro = new javax.swing.JTable();
        txt_nome2 = new javax.swing.JTextField();
        cpf = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JTextField();
        sexo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbo_estado = new javax.swing.JComboBox();
        txt_cep = new javax.swing.JTextField();
        cep = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nome.setText("nome");

        cidade.setText("cidade");

        opt_masc.setText("masculino");
        opt_masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_mascActionPerformed(evt);
            }
        });

        opt_fem.setText("feminino");
        opt_fem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_femActionPerformed(evt);
            }
        });

        turma.setText("turma");

        cbo_turma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1º Ano", "2º Ano", "3º Ano" }));

        obs.setColumns(20);
        obs.setRows(5);
        obs.setEnabled(false);
        jScrollPane2.setViewportView(obs);

        chk_atv_des.setText("Inserir Observações");
        chk_atv_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_atv_desActionPerformed(evt);
            }
        });

        btn_cadastrar.setText("Cadastrar Informações");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        tbl_cadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nome", "sexo", "cpf", "cidade", "estado", "turma", "cep", "observações"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_cadastro);

        cpf.setText("cpf");

        sexo.setText("sexo");

        jLabel9.setText("estado");

        cbo_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acre", "Amapá ", "Amazonas ", "Pará", "Rondônia", "Roraima ", "Tocantins ", "Alagoas ", "Bahia ", "Ceará ", "Maranhão ", "Paraíba ", "Pernambuco ", "Piauí ", "Rio Grande do Norte", "Sergipe ", "Goiás", "Mato Grosso", "Mato Grosso do Sul", "Distrito Federal ", "Espírito Santo ", "Minas Gerais", "São Paulo ", "Rio de Janeiro ", "Paraná", "Rio Grande do Sul", "Santa Catarina " }));

        cep.setText("cep");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(nome))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sexo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(opt_masc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opt_fem)
                                .addGap(138, 138, 138)
                                .addComponent(cpf)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbo_turma, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chk_atv_des))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(turma)
                        .addGap(219, 219, 219)
                        .addComponent(cep)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cadastrar)
                .addGap(187, 187, 187))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(txt_nome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt_masc)
                    .addComponent(opt_fem)
                    .addComponent(cpf)
                    .addComponent(sexo)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidade)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbo_turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(turma)
                        .addComponent(cep)))
                .addGap(30, 30, 30)
                .addComponent(chk_atv_des)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opt_mascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_mascActionPerformed

        // deixar a opção feminina desabilitada

        opt_fem.setSelected(false);

    }//GEN-LAST:event_opt_mascActionPerformed

    private void opt_femActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_femActionPerformed

        // deixar a opção masculino desabilitada
        opt_masc.setSelected(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_opt_femActionPerformed

    private void chk_atv_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_atv_desActionPerformed

        // se a caixa estiver selecionada
        if ( chk_atv_des.isSelected())  {

            // habilitar o campo informações
            obs.setEnabled(true);
            

        } else {

            // caso contrário irá limpar e desabilitar o campo informação

            obs.setText("");

            obs.setEnabled(false);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_chk_atv_desActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed

        // pegando os dados digitados pelo usúario e inserindo na váriavel nome
        String nome = (String) txt_nome2.getText();

        String cpf= (String) txt_cpf.getText();

        String sexo;

        // se for selecionada a opção feminino a variável sexo recebe o texto do radion button ( feminino)

        if ( opt_fem.isSelected())  {

            sexo = opt_fem.getText();

            // se for selecionada a opção masculino variável sexo recebe o texto do radion button ( masculino)
        } else if ( opt_masc.isSelected()) {

            sexo = opt_masc.getText();

            // caso contrário será castrado em  branco
        } else{

            sexo = "";
        }

        
        
        // pegando a informação do JCombobox e inserindo na variável esco
        String turma = (String) cbo_turma.getSelectedItem();
         String obs1 = (String) obs.getText();

        String cep = (String) txt_cep.getText();

        String cidade = (String) txt_cidade.getText();
        String estado = (String) cbo_estado.getSelectedItem();
        //  Adicionar o import javax.swing.table.DefaultTableModel;

        // definir o nome do modelo de Tabela ( ModelCadastro) e obter o modelo da tabela( tbl_cadastro)
        DefaultTableModel ModelCadastro = (DefaultTableModel) tbl_cadastro.getModel();

        // criar um objeto( informacoes) e passar para ele os parametros( variaveis), por ordem de inserção

        Object[] informacoes ={nome,sexo,cpf,cidade,estado,turma,cep,obs1};

        // adicionar as informações na tabela
        ModelCadastro.addRow(informacoes);

        // limpar os campos para inserir novo cadastro

        txt_cidade.setText("");


        opt_fem.setSelected(false);

        opt_masc.setSelected(false);

        cbo_turma.setSelectedIndex(0);
        
        txt_nome2.setText("");
        opt_masc.setSelected(false);
        opt_fem.setSelected(false);
        txt_cpf.setText("");
        txt_cidade.setText("");
        txt_cep.setText("");
        obs.setText("");
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JComboBox cbo_estado;
    private javax.swing.JComboBox cbo_turma;
    private javax.swing.JLabel cep;
    private javax.swing.JCheckBox chk_atv_des;
    private javax.swing.JLabel cidade;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nome;
    private javax.swing.JTextArea obs;
    private javax.swing.JRadioButton opt_fem;
    private javax.swing.JRadioButton opt_masc;
    private javax.swing.JLabel sexo;
    private javax.swing.JTable tbl_cadastro;
    private javax.swing.JLabel turma;
    private javax.swing.JTextField txt_cep;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_nome1;
    private javax.swing.JTextField txt_nome2;
    // End of variables declaration//GEN-END:variables
}
